import { writeFileSync, existsSync, readFileSync } from 'fs'
import { join } from 'path'

const projectRoot = process.cwd()
const dbPath = join(projectRoot, 'db', 'custom.db').replace(/\\/g, '/')
const envPath = join(projectRoot, '.env')

const envContent = `# Auto-generated by init-env.mjs
DATABASE_URL=file:${dbPath}
`

const existing = existsSync(envPath) ? readFileSync(envPath, 'utf-8') : ''

if (existing.includes('DATABASE_URL=file:') && !existing.includes('#')) {
  const updated = existing.replace(/^DATABASE_URL=file:.*$/m, `DATABASE_URL=file:${dbPath}`)
  if (updated !== existing) {
    writeFileSync(envPath, updated, 'utf-8')
    console.log(`Updated .env: DATABASE_URL=file:${dbPath}`)
  }
} else {
  writeFileSync(envPath, envContent, 'utf-8')
  console.log(`Created .env: DATABASE_URL=file:${dbPath}`)
}
